### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by crynobone** [katsana/minions#1]
* [x] Usage guide
* [x] Concept
* [ ] Request Authentication

**Comment by faizalmansor** [comment]
I'm interested to help. How to start contributing for this documentation?

**Comment by crynobone** [comment]
https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html

Can just copy and paste the SSL configurations from `laravel-websockets` since it's almost similar
